### ISSUE TITLE
About local covariance 

### ISSUE THREAD

**Issue by AlphaPav** [AnTao97/UnsupervisedPointCloudFeatureLearning#1]
Hi,
Thanks for releasing the code! I am very interested in your implementation of FoldingNet!
 
https://github.com/AnTao97/UnsupervisedPointCloudReconstruction/blob/6c8b56c2d9eaceb2eb5ec7cf27e71c48014558cd/model.py#L49
In this line, why the local covariance is computed by using the positions of top 2 out of top k neighbors?

The original implementation of FoldingNet uses numpy.cov() to compute the local covariance matrix for k points. 

I guess the local covariance computed by these two methods are not equal?

**Comment by antao97** [comment]
Hi @AlphaPav,

Thanks you so much of your note! I do make a mistake in this part.

I revise it in my code, and then run FoldingNet experiment with my new code and get 88.3% in ModelNet40. It seems that my incorrect implementation of local covariance can do a better job than the proposed one. Or since 88.3% and 88.4% are almost same, the local covariance makes few contribution to overall performance.

Anyhow, I will point out this issue in README.

**Comment by antao97** [comment]
Hi @AlphaPav , 

I also run an experiment without local covariance, i.e. the size of the first MLP layer is (3, 64). The result on ModelNet40 is 88.6%. 

It seems that the network works better without local covariance, or the local covariance indeed makes very few contribution.

**Comment by AlphaPav** [comment]
Hi @AnTao97 ,

Sounds good! Many thanks!!
